# Generated by Django 5.2.7 on 2025-10-28 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_remove_schoolclass_teacher_lesson_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='lesson',
        ),
        migrations.AddField(
            model_name='lesson',
            name='topics',
            field=models.ManyToManyField(blank=True, related_name='lessons', to='school.topic'),
        ),
    ]
