# Generated by Django 5.2.7 on 2025-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0006_remove_student_school_class_schoolclass_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='maximin_questions',
            field=models.IntegerField(default=0),
        ),
    ]
