# Generated by Django 5.2.7 on 2025-11-02 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_test_maximin_questions'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_assigned', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_topics', to='school.teacher')),
                ('school_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_topics', to='school.schoolclass')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to_classes', to='school.topic')),
            ],
        ),
    ]
