# Generated by Django 5.2.7 on 2025-11-02 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0008_assignedtopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtopic',
            name='title',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
