# Generated by Django 5.2.7 on 2025-11-22 12:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_test_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='assigned_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.assignedtopic'),
        ),
        migrations.AddField(
            model_name='testresult',
            name='assigned_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.assignedtopic'),
        ),
    ]
