# Generated by Django 5.2.7 on 2025-11-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_test_assigned_topic_testresult_assigned_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtopic',
            name='question_count',
            field=models.IntegerField(default=0),
        ),
    ]
