# Generated by Django 5.2.7 on 2025-11-23 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_assignedtopic_question_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tasks_count', models.PositiveIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_checked', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.student')),
                ('test_result', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='homework', to='school.testresult')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.assignedtopic')),
            ],
        ),
        migrations.CreateModel(
            name='HomeworkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=1)),
                ('text', models.TextField()),
                ('solution', models.TextField()),
                ('correct_answer', models.CharField(max_length=50)),
                ('student_answer', models.CharField(blank=True, max_length=50)),
                ('is_correct', models.BooleanField(null=True)),
                ('homework', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='school.homework')),
            ],
        ),
    ]
