# Generated by Django 5.2.7 on 2025-11-30 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_alter_assignedtopic_options_alter_homework_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedtopic',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='homework',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
