# Generated by Django 5.2.7 on 2025-11-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0017_assignedtopic_deadline_homework_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='schoolclass',
            name='subjects',
            field=models.ManyToManyField(related_name='classes', to='school.subject'),
        ),
    ]
