# Generated by Django 5.2.7 on 2025-12-01 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_schoolclass_subjects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedtopic',
            name='topic',
        ),
    ]
