# Generated by Django 5.2.7 on 2025-12-01 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_assignedtopic_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignedtopic',
            options={'verbose_name': 'Назначенный урок', 'verbose_name_plural': 'Назначенные уроки'},
        ),
        migrations.RemoveField(
            model_name='homework',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='test',
            name='topic',
        ),
        migrations.AddField(
            model_name='assignedtopic',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_topics', to='school.lesson'),
        ),
        migrations.AddField(
            model_name='homework',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homeworks', to='school.lesson'),
        ),
    ]
