# Generated by Django 5.2.7 on 2026-05-11 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_alter_assignedtopic_options_remove_homework_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeworkAppeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_comment', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'На рассмотрении'), ('resolved', 'Рассмотрено')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('homework', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='appeal', to='school.homework')),
            ],
            options={
                'verbose_name': 'Апелляция по ДЗ',
                'verbose_name_plural': 'Апелляции по ДЗ',
            },
        ),
        migrations.CreateModel(
            name='HomeworkAppealTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_verdict', models.BooleanField(null=True)),
                ('teacher_comment', models.TextField(blank=True)),
                ('appeal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_tasks', to='school.homeworkappeal')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeal_tasks', to='school.homeworktask')),
            ],
            options={
                'verbose_name': 'Задача в апелляции',
                'verbose_name_plural': 'Задачи в апелляции',
            },
        ),
    ]
