# Generated by Django 5.2.7 on 2026-05-11 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_appeal_models'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeworkappealtask',
            name='reason',
            field=models.CharField(choices=[('answer', 'Не согласен с ответом'), ('solution', 'Не согласен с решением')], default='answer', max_length=20),
        ),
        migrations.AddField(
            model_name='homeworkappealtask',
            name='student_note',
            field=models.TextField(blank=True),
        ),
    ]
